# Generated by Django 5.1.2 on 2024-11-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventManager", "0002_customer_first_name_alter_customer_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="ელ.ფოსტის მისამართი"),
        ),
    ]
