# Generated by Django 5.1.2 on 2024-11-24 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventManager", "0003_alter_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="stadium",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="eventManager.stadium",
            ),
        ),
    ]
