# Generated by Django 5.1.2 on 2024-12-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventManager", "0005_alter_event_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizerCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "events_organized",
                    models.ManyToManyField(
                        related_name="companies", to="eventManager.event"
                    ),
                ),
            ],
        ),
    ]
