# Generated by Django 5.1.2 on 2024-12-01 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventManager", "0006_organizercompany"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizercompany",
            options={
                "verbose_name": "ორგანიზატორი კომპანია",
                "verbose_name_plural": "ორგანიზატორი კომპანიები",
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="stadium",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="eventManager.stadium",
            ),
        ),
    ]
